/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public static void main(String[] args) {

        System.out.println("Welcome to 'Is Palindrome'!");
        
        // gather inputr from user and determine if if is 
        // a palindrome or not. 
        Palindrome test = new Palindrome();
        String word = test.UserInput();
        Boolean True_False = test.IsPalindrome(word);

        //print result to screen
        System.out.println(True_False);
    }
}
