/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Palindrome test = new Palindrome();
        String word = test.UserInput();
        Boolean True_False = test.IsPalindrome(word);
        System.out.println(True_False);
    }
}
